// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS6ybsgb3b1jqNsPpqOpZIzB0d3XKtd-U',
    appId: '1:547794374983:web:a2053115b4e7cdce14bc62',
    messagingSenderId: '547794374983',
    projectId: 'todo-app-d7d9d',
    authDomain: 'todo-app-d7d9d.firebaseapp.com',
    storageBucket: 'todo-app-d7d9d.appspot.com',
    measurementId: 'G-FWYZE9WFYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9hbRw1CDGFZrNyMUzgXblyBTHn_eGFeU',
    appId: '1:547794374983:android:806e00126a0ababe14bc62',
    messagingSenderId: '547794374983',
    projectId: 'todo-app-d7d9d',
    storageBucket: 'todo-app-d7d9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyWjtxOzKjWPH1SuuKeJtad8-KV3l13S8',
    appId: '1:547794374983:ios:ca93bc6a09e0a9b714bc62',
    messagingSenderId: '547794374983',
    projectId: 'todo-app-d7d9d',
    storageBucket: 'todo-app-d7d9d.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyWjtxOzKjWPH1SuuKeJtad8-KV3l13S8',
    appId: '1:547794374983:ios:de049281096afcd114bc62',
    messagingSenderId: '547794374983',
    projectId: 'todo-app-d7d9d',
    storageBucket: 'todo-app-d7d9d.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
